
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/explorer-gps

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-]
      - run:
          name: Install (development)
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit Tests
          command: npm run test
      - persist_to_workspace:
          root: ~/
          paths:
            - explorer-gps

  deploy:
      docker:
        - image: circleci/node:8
      working_directory: ~/
      
      steps:
        - attach_workspace:
            at: ./
        - run: cd explorer-gps && ls -la
        - run:
            name: Install AWS CLI
            command: sudo apt-get install python-dev build-essential python-pip && sudo pip install awscli
        - run:
            name: Cleanup dev dependencies
            command: npm prune --production
        - run: ls -la
        - run:
            name: Create Package
            command: zip ~/explorer-gps.zip * --exclude=.*
        - run:
            name: Deploy to S3
            command: aws s3 cp ~/explorer-gps.zip s3://explorer-deploy/explorer-gps/explorer-gps.zip

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master