
version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8
    working_directory: ~/explorer-gps

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-]
      - run:
          name: Install
          command: npm install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Lint
          command: npm run lint
      - run:
          name: Unit Tests
          command: npm run test
      - persist_to_workspace:
          root: ~/
          paths:
            - explorer-gps

  deploy:
      docker:
        - image: circleci/node:8
      working_directory: ~/explorer-gps

      steps:
        - attach_workspace:
            at: ~/
        - run:
            name: Install AWS CLI
            command: sudo apt-get install python-dev build-essential python-pip && sudo pip install awscli
        - run: cd ~/explorer-gps
        - run:
            name: Prune dependencies
            command: npm prune --production
        - run:
            name: Copy Environment Variables
            command: |
                ENV_FILE=.env
                echo "AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID" >> $ENV_FILE
                echo "AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY" >> $ENV_FILE
        - run:
            name: Install Docker client
            command: |
                set -x
                VER="17.03.0-ce"
                curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
                tar -xz -C /tmp -f /tmp/docker-$VER.tgz
                sudo mv /tmp/docker/* /usr/bin -f
        - run:
            name: Build Docker Container
            command: docker build -t explorer-gps .
        - run:
            name: Push Docker Image to ECR
            command: |
              DOCKER_IMAGE=explorer-gps
              AWS_REGION=us-east-1
              # Login to AWS
              aws configure set region $AWS_REGION
              $(aws ecr get-login)
              # Tag and push docker image
              docker tag app $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:latest
              docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$DOCKER_IMAGE:latest

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master